// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ragnarok_Mobile_Website.Models;

namespace Ragnarok_Mobile_Website.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20200918205851_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Ragnarok_Mobile_Website.Models.AdventureBook", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalAttack")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.ToTable("AdventureBook");
                });

            modelBuilder.Entity("Ragnarok_Mobile_Website.Models.CharacterStats", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoldMedals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildContribution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("Ragnarok_Mobile_Website.Models.ClassStats", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicDamageIgnore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicDefenseIgnore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicPenetration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalDamageReduction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalDefenseIgnore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalPenetration")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassId");

                    b.ToTable("ClassStat");
                });

            modelBuilder.Entity("Ragnarok_Mobile_Website.Models.Equipment", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArmorCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmorName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArmorRefine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackName")
                        .HasColumnType("TEXT");

                    b.Property<int>("BackRefine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FaceName")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaceRefine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadgearCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadgearName")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeadgearRefine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeftAccessoryCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeftAccessoryName")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeftAccessoryRefine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManteauCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManteauName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManteauRefine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MouthName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MouthRefine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RightAccessoryCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("RightAccessoryName")
                        .HasColumnType("TEXT");

                    b.Property<int>("RightAccessoryRefine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShieldCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShieldName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShieldRefine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TailName")
                        .HasColumnType("TEXT");

                    b.Property<int>("TailRefine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponName")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeaponRefine")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Ragnarok_Mobile_Website.Models.Guild", b =>
                {
                    b.Property<int>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildName")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("Guild");
                });

            modelBuilder.Entity("Ragnarok_Mobile_Website.Models.PrayerTracker", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicalDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalDefense")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.ToTable("PrayerTracker");
                });

            modelBuilder.Entity("Ragnarok_Mobile_Website.Models.StatusResistance", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FearResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreezeResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetrifyResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SleepResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StunResistance")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.ToTable("StatusResistance");
                });

            modelBuilder.Entity("Ragnarok_Mobile_Website.Models.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
